const list = [
    {
      id: 1,
      title: "Cheeseburger Menu",
      author: "200 gr dana eti,cheedar peyniri,yeşillik,domates,soğan,özel burger sos,patates kızartması,içecek",
      price: 50,
      img: "https://www.soke.com.tr/Files/tarifler/HamburgerEkmegi3.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Tavuk Barbekü Menü",
      author: "200 gr tavuk eti,çıtır patates,turşu,chedar peyniri,ketçap,patates kızartması,içecek",
      price: 40,
      img: "http://mamys.com.tr/image/cache/catalog/product1/Mamy's%20Chicken%20Barbecue-600x600.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Pastırma Burger Menü",
      author: "2x200 gr dana eti,2x chedar peyniri,pastırma,patates kızartması,içecek",
      price: 70,
      img: "http://mamys.com.tr/image/catalog/urunler/past%C4%B1rmator.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Jalepeno Burger Menü",
      author: "200 gr dana eti, chedar peyniri,jalepeno biberi,acı sos,domates,soğan,yeşillik,özel burger sos,patates kızartması,içecek",
      price: 55,
      img: "http://mamys.com.tr/image/catalog/urunler/jalapeno.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "Çocuk Menü",
      author: "100 gr dana eti,ketçap,patates kızartması,içecek",
      price: 30,
      img: "http://mamys.com.tr/image/cache/catalog/Kids%20Meal%20Hamburger%20Men%C3%BC-600x600.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Tavuk Tenders Menü",
      author: "6 lı tenders,patates kızartması,içecek",
      price: 35,
      img: "http://mamys.com.tr/image/catalog/cmsblock/block1-home11.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Kavurma Burger Menü ",
      author: "200 gr kavurma eti,chedar peyniri,çıtır patates,patetes kızartması,içecek",
      price: 80,
      img: "http://mamys.com.tr/image/cache/catalog/Kavurma%20Men%C3%BC-600x600.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Ranch Soslu Tavuk Wrap Menü",
      author: "150 gr tavuk,yeşillik,chedar peyniri,ranch sos,patates kızartması,içecek",
      price: 40,
      img: "http://mamys.com.tr/image/cache/catalog/product1/Ranch%20Chicken%20Wrap%20Men%C3%BC-235x235.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Big Burger Menü ",
      author: "2x200 gr dana eti,2x chedar peyniri,turşu,yeşillik,soğan,özel burger sos,patates kızartması,içecek",
      price: 75,
      img: "http://mamys.com.tr/image/cache/catalog/Big%20Mamy%20Men%C3%BC-600x600.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Tavuk Izgara Burger Menü",
      author: "200 gr ızgara tavuk eti,domates,yeşillik,mayonez,patates kızartması,içecek",
      price: 45,
      img: "http://mamys.com.tr/image/cache/catalog/Chicken%20Grill%20%20Men%C3%BC-600x600.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Double Cheeseburger Menü",
      author: "2x200 gr dana eti,2x chedar peyniri,turşu,karamelize soğan,yeşillik,özel burger sos,patates kızartması,içecek",
      price: 80,
      img: "http://mamys.com.tr/image/cache/catalog/Super%20Cheeseburger%20Men%C3%BC-600x600.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Füme Menü",
      author: "200 gr dana eti,çıtır patates,füme eti,chedar peyniri,barbekü sos,patates kızartması,içecek",
      price: 70,
      img: "http://mamys.com.tr/image/cache/catalog/F%C3%BCme%20Men%C3%BC-600x600.jpg",
      amount: 1,
    },
  ];
  
  export default list;